os:
  - linux

language: go

go:
  - 1.13.x

env:
  matrix:
    - GOTFLAGS="-race"
    - GOTFLAGS=""
  global:
    - IPFS_REUSEPORT=false
    - BUILD_DEPTYPE=gomod


# disable travis install
install:
  - true

script:
  - bash <(curl -s https://raw.githubusercontent.com/ipfs/ci-helpers/master/travis-ci/run-standard-tests.sh)


cache:
  directories:
    - $GOPATH/pkg/mod
    - /home/travis/.cache/go-build

notifications:
  email: false
